const SellersData = [
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
    {
        _id: 497849,
        name: 'Anonymous',
        email: 'randomperson@gmail.com',
        phone: 97876952347,
        type: 'retailer',
        level: 'level2',
    },
]
export default SellersData