const StaticProductsTable = [
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
    {
        image: 'https://cdn.w600.comps.canstockphoto.com/jar-of-perfume-icon-simple-style-stock-illustrations_csp47888374.jpg',
        title: 'Cookie',
        measuringUnit: 'kg',
        date: '03/09/2022',
        location: 'Random',
        price: '$750',
    },
]
export default StaticProductsTable